spring.application.name=BE_SEP490_G67
server.port=${PORT:8080}
# ===================================
# Database Configuration (MySQL)
# ===================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/dbdev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===================================
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

jwt.secretKey=mysupersecretkeymysupersecretkey123
jwt.expiration=86400000
jwt.refresh-duration=36000000

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

esms.api-key=220AFC15DF02320DE200239456C966
esms.secret-key=CAED7E9C1FBC7FD0371B8E5B59DF1B
esms.sms-type=8
esms.url= https://rest.esms.vn/MainService.svc/json/SendMultipleMessage_V4_post_json/

infobip.api.key=9b20ad842fea954b3833dd5328b0c412-1cb8061f-fed3-4a4c-8240-5279c65ee626
infobip.base.url=https://4k2m61.api.infobip.com
