import { CHECK_STATUS } from '../constants';

export const MOCK_INVENTORY_CHECKS = [
    {
        id: 'PKK-20231027-01',
        code: 'PKK-20231027-01',
        checkDate: '2023-10-28T14:15:00',
        checker: 'Trần Thị B (QL)',
        note: 'Kiểm kho định kỳ tháng 10',
        status: CHECK_STATUS.COMPLETED,
        warehouse: 'Kho chính - CH01',
        createdAt: '2023-10-27T08:30:00',
        createdBy: 'Nguyễn Văn A (Kho)',
        generalNote:
            'Kiểm kho định kỳ tháng 10. Phát hiện thiếu 8 sản phẩm tại khu A do hư hỏng và nhầm lẫn khi xếp kệ.',
    },
    {
        id: 'PKK-20231015-01',
        code: 'PKK-20231015-01',
        checkDate: '2023-10-15T14:30:00',
        checker: 'Nguyễn Văn A',
        note: 'Kiểm kho định kỳ tháng 10',
        status: CHECK_STATUS.COMPLETED,
        warehouse: 'Kho chính - CH01',
        createdAt: '2023-10-15T09:00:00',
        createdBy: 'Nguyễn Văn A',
        generalNote: '',
    },
    {
        id: 'PKK-20231020-02',
        code: 'PKK-20231020-02',
        checkDate: '2023-10-20T10:00:00',
        checker: 'Lê Văn C',
        note: 'Kiểm đột xuất khu B',
        status: CHECK_STATUS.IN_PROGRESS,
        warehouse: 'Kho chính - CH01',
        createdAt: '2023-10-20T08:00:00',
        createdBy: 'Lê Văn C',
        generalNote: 'Đang kiểm khu B, khu A hoàn thành.',
    },
    {
        id: 'PKK-20231012-03',
        code: 'PKK-20231012-03',
        checkDate: '2023-10-12T16:00:00',
        checker: 'Phạm Thị D',
        note: 'Hủy do nhập sai dữ liệu',
        status: CHECK_STATUS.CANCELLED,
        warehouse: 'Kho chính - CH01',
        createdAt: '2023-10-12T15:00:00',
        createdBy: 'Phạm Thị D',
        generalNote: '',
    },
    {
        id: 'PKK-20231018-04',
        code: 'PKK-20231018-04',
        checkDate: '2023-10-18T11:30:00',
        checker: 'Nguyễn Văn A',
        note: 'Kiểm kệ A-01',
        status: CHECK_STATUS.COMPLETED,
        warehouse: 'Kho chính - CH01',
        createdAt: '2023-10-18T09:30:00',
        createdBy: 'Nguyễn Văn A',
        generalNote: '',
    },
];

/** Mỗi dòng kiểm = 1 lô + 1 vị trí kệ (mỗi kệ chỉ 1 loại SP) */
export const MOCK_CHECK_LINES = {
    'PKK-20231027-01': [
        {
            id: 'line-1',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            batchCode: 'BATCH-101',
            locationLabel: 'A-01-02',
            systemQty: 60,
            actualQty: 58,
            importPrice: 10000,
            note: 'Hư hỏng',
        },
        {
            id: 'line-1b',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            batchCode: 'BATCH-119',
            locationLabel: 'A-01-02',
            systemQty: 24,
            actualQty: 24,
            importPrice: 10200,
            note: '',
        },
        {
            id: 'line-2',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            batchCode: 'BATCH-101',
            locationLabel: 'B-03-01',
            systemQty: 40,
            actualQty: 40,
            importPrice: 10000,
            note: '',
        },
        {
            id: 'line-3',
            productCode: 'SP00089',
            productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
            unit: 'Hộp',
            batchCode: 'BATCH-205',
            locationLabel: 'A-01-03',
            systemQty: 85,
            actualQty: 85,
            importPrice: 32000,
            note: '',
        },
        {
            id: 'line-4',
            productCode: 'SP00201',
            productName: 'Trứng gà ta',
            unit: 'Quả',
            batchCode: 'BATCH-088',
            locationLabel: 'A-02-01',
            systemQty: 31,
            actualQty: 32,
            importPrice: 4500,
            note: '',
        },
        {
            id: 'line-5',
            productCode: 'SP00042',
            productName: 'Gạo ST25 Hạt Ngọc Trời 5kg',
            unit: 'Bao',
            batchCode: 'BATCH-312',
            locationLabel: 'A-03-02',
            systemQty: 24,
            actualQty: 24,
            importPrice: 125000,
            note: '',
        },
    ],
    'PKK-20231015-01': [
        {
            id: 'line-1',
            productCode: 'SP00105',
            productName: 'Dầu ăn Simply 1L',
            unit: 'Chai',
            batchCode: 'BATCH-077',
            locationLabel: 'B-01-01',
            systemQty: 50,
            actualQty: 50,
            importPrice: 45000,
            note: '',
        },
    ],
    'PKK-20231020-02': [
        {
            id: 'line-1',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            batchCode: 'BATCH-101',
            locationLabel: 'B-03-01',
            systemQty: 40,
            actualQty: null,
            importPrice: 10000,
            note: '',
        },
    ],
};

/** Dùng cho form tạo phiếu — mỗi dòng = 1 lô tại 1 kệ (1 kệ chỉ 1 loại SP) */
export const MOCK_AVAILABLE_BATCH_LOCATIONS = [
    {
        id: 'bl-1',
        productCode: 'SP00124',
        productName: 'Nước giải khát Coca Cola 330ml',
        unit: 'Lon',
        batchCode: 'BATCH-101',
        locationLabel: 'A-01-02',
        systemQty: 60,
        importPrice: 10000,
        expiryDate: '2026-12-31',
    },
    {
        id: 'bl-1b',
        productCode: 'SP00124',
        productName: 'Nước giải khát Coca Cola 330ml',
        unit: 'Lon',
        batchCode: 'BATCH-119',
        locationLabel: 'A-01-02',
        systemQty: 24,
        importPrice: 10200,
        expiryDate: '2026-08-15',
    },
    {
        id: 'bl-2',
        productCode: 'SP00124',
        productName: 'Nước giải khát Coca Cola 330ml',
        unit: 'Lon',
        batchCode: 'BATCH-101',
        locationLabel: 'B-03-01',
        systemQty: 40,
        importPrice: 10000,
        expiryDate: '2026-12-31',
    },
    {
        id: 'bl-3',
        productCode: 'SP00089',
        productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
        unit: 'Hộp',
        batchCode: 'BATCH-205',
        locationLabel: 'A-01-03',
        systemQty: 85,
        importPrice: 32000,
        expiryDate: '2026-11-30',
    },
    {
        id: 'bl-4',
        productCode: 'SP00201',
        productName: 'Trứng gà ta',
        unit: 'Quả',
        batchCode: 'BATCH-088',
        locationLabel: 'A-02-01',
        systemQty: 31,
        importPrice: 4500,
        expiryDate: '2026-06-15',
    },
    {
        id: 'bl-5',
        productCode: 'SP00042',
        productName: 'Gạo ST25 Hạt Ngọc Trời 5kg',
        unit: 'Bao',
        batchCode: 'BATCH-312',
        locationLabel: 'A-03-02',
        systemQty: 24,
        importPrice: 125000,
        expiryDate: '2027-01-31',
    },
    {
        id: 'bl-6',
        productCode: 'SP00331',
        productName: 'Pepsi 330ml',
        unit: 'Lon',
        batchCode: 'BATCH-118',
        locationLabel: 'A-02-02',
        systemQty: 36,
        importPrice: 9500,
        expiryDate: '2026-09-20',
    },
    {
        id: 'bl-7',
        productCode: 'SP00156',
        productName: 'Nước mắm Nam Ngư 750ml',
        unit: 'Chai',
        batchCode: 'BATCH-220',
        locationLabel: 'B-02-01',
        systemQty: 48,
        importPrice: 28000,
        expiryDate: '2027-06-30',
    },
    {
        id: 'bl-8',
        productCode: 'SP00178',
        productName: 'Mì Hảo Hảo tôm chua cay',
        unit: 'Gói',
        batchCode: 'BATCH-301',
        locationLabel: 'B-01-01',
        systemQty: 120,
        importPrice: 3200,
        expiryDate: '2026-09-20',
    },
    {
        id: 'bl-9',
        productCode: 'SP00412',
        productName: "Kem Wall's Magnum Classic",
        unit: 'Cây',
        batchCode: 'BATCH-045',
        locationLabel: 'C-01-03',
        systemQty: 18,
        importPrice: 22000,
        expiryDate: '2026-06-18',
    },
];

export const MOCK_LOCATIONS = [
    { value: 'all', label: 'Tất cả vị trí' },
    { value: 'A-01-02', label: 'A-01-02 (Khu A)' },
    { value: 'A-01-03', label: 'A-01-03 (Khu A)' },
    { value: 'A-02-01', label: 'A-02-01 (Khu A)' },
    { value: 'A-02-02', label: 'A-02-02 (Khu A)' },
    { value: 'A-03-02', label: 'A-03-02 (Khu A)' },
    { value: 'B-01-01', label: 'B-01-01 (Khu B)' },
    { value: 'B-02-01', label: 'B-02-01 (Khu B)' },
    { value: 'B-03-01', label: 'B-03-01 (Khu B)' },
    { value: 'C-01-03', label: 'C-01-03 (Khu C)' },
];

export function getInventoryCheckById(id) {
    return MOCK_INVENTORY_CHECKS.find((item) => item.id === id) ?? null;
}

export function getCheckLinesById(id) {
    return MOCK_CHECK_LINES[id] ?? [];
}
