export const NOTIFICATION_TYPES = {
    DEBT_CUSTOMER_REVIEW: 'DEBT_CUSTOMER_REVIEW',
    OVERDUE_DEBT: 'OVERDUE_DEBT',
    LOW_STOCK: 'LOW_STOCK',
    EXPIRED: 'EXPIRED',
    NEAR_EXPIRED: 'NEAR_EXPIRED',
};

export const NOTIFICATION_TYPE_LABELS = {
    [NOTIFICATION_TYPES.DEBT_CUSTOMER_REVIEW]: 'Khách nợ mới',
    [NOTIFICATION_TYPES.OVERDUE_DEBT]: 'Nợ quá hạn',
    [NOTIFICATION_TYPES.LOW_STOCK]: 'Sắp hết hàng',
    [NOTIFICATION_TYPES.EXPIRED]: 'Hết hạn',
    [NOTIFICATION_TYPES.NEAR_EXPIRED]: 'Cận hạn',
};

/** Các chip lọc theo loại hiện trên panel. */
export const NOTIFICATION_TYPE_FILTERS = [
    NOTIFICATION_TYPES.LOW_STOCK,
    NOTIFICATION_TYPES.NEAR_EXPIRED,
    NOTIFICATION_TYPES.EXPIRED,
    NOTIFICATION_TYPES.OVERDUE_DEBT,
    NOTIFICATION_TYPES.DEBT_CUSTOMER_REVIEW,
];

export const NOTIFICATION_PAGE_SIZE = 10;
