/**
 * Mock vị trí kho.
 * Khu kho / khu bán: 1 ô có thể nhiều SP / nhiều lô.
 * Khu bán: 1 ô nhiều SP; cùng 1 lô được tách nhiều ô; mỗi SP chỉ 1 mã lô trên khu bán.
 */
export const MOCK_STORAGE_LOCATIONS = [
    {
        id: 1,
        label: 'A-01-01',
        zone: 'A',
        zoneTitle: 'Khu nước giải khát & sữa',
        aisle: '01',
        shelf: '01',
        bin: null,
        description: 'Kệ đầu hàng A, dành cho hàng mới nhập',
        contents: [],
    },
    {
        id: 2,
        label: 'A-01-02',
        zone: 'A',
        zoneTitle: 'Khu nước giải khát & sữa',
        aisle: '01',
        shelf: '02',
        bin: null,
        description: 'Kệ nước ngọt Coca, tầng mắt',
        contents: [
            {
                id: 'bl-1',
                productCode: 'SP00124',
                productName: 'Nước giải khát Coca Cola 330ml',
                unit: 'Lon',
                batchCode: 'BATCH-101',
                quantity: 60,
                importPrice: 10000,
                expiryDate: '2026-12-31',
            },
            {
                id: 'bl-1b',
                productCode: 'SP00124',
                productName: 'Nước giải khát Coca Cola 330ml',
                unit: 'Lon',
                batchCode: 'BATCH-119',
                quantity: 24,
                importPrice: 10200,
                expiryDate: '2026-08-15',
            },
        ],
    },
    {
        id: 3,
        label: 'A-01-03',
        zone: 'A',
        zoneTitle: 'Khu nước giải khát & sữa',
        aisle: '01',
        shelf: '03',
        bin: null,
        description: 'Kệ sữa tươi Vinamilk',
        contents: [
            {
                id: 'bl-3',
                productCode: 'SP00089',
                productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
                unit: 'Hộp',
                batchCode: 'BATCH-205',
                quantity: 85,
                importPrice: 32000,
                expiryDate: '2026-11-30',
            },
        ],
    },
    {
        id: 4,
        label: 'A-02-01',
        zone: 'A',
        zoneTitle: 'Khu nước giải khát & sữa',
        aisle: '02',
        shelf: '01',
        bin: null,
        description: 'Kệ trứng gà ta',
        contents: [
            {
                id: 'bl-4',
                productCode: 'SP00201',
                productName: 'Trứng gà ta',
                unit: 'Quả',
                batchCode: 'BATCH-088',
                quantity: 31,
                importPrice: 4500,
                expiryDate: '2026-06-15',
            },
        ],
    },
    {
        id: 5,
        label: 'A-02-02',
        zone: 'A',
        zoneTitle: 'Khu nước giải khát & sữa',
        aisle: '02',
        shelf: '02',
        bin: null,
        description: 'Kệ nước ngọt Pepsi',
        contents: [
            {
                id: 'bl-6',
                productCode: 'SP00331',
                productName: 'Pepsi 330ml',
                unit: 'Lon',
                batchCode: 'BATCH-118',
                quantity: 36,
                importPrice: 9500,
                expiryDate: '2026-09-20',
            },
        ],
    },
    {
        id: 6,
        label: 'A-03-02',
        zone: 'A',
        zoneTitle: 'Khu nước giải khát & sữa',
        aisle: '03',
        shelf: '02',
        bin: null,
        description: 'Kệ gạo ST25',
        contents: [
            {
                id: 'bl-5',
                productCode: 'SP00042',
                productName: 'Gạo ST25 Hạt Ngọc Trời 5kg',
                unit: 'Bao',
                batchCode: 'BATCH-312',
                quantity: 24,
                importPrice: 125000,
                expiryDate: '2027-01-31',
            },
        ],
    },
    {
        id: 7,
        label: 'B-01-01',
        zone: 'B',
        zoneTitle: 'Khu khô & gia vị',
        aisle: '01',
        shelf: '01',
        bin: null,
        description: 'Kệ mì gói Hảo Hảo',
        contents: [
            {
                id: 'bl-8',
                productCode: 'SP00178',
                productName: 'Mì Hảo Hảo tôm chua cay',
                unit: 'Gói',
                batchCode: 'BATCH-301',
                quantity: 120,
                importPrice: 3200,
                expiryDate: '2026-09-20',
            },
        ],
    },
    {
        id: 8,
        label: 'B-02-01',
        zone: 'B',
        zoneTitle: 'Khu khô & gia vị',
        aisle: '02',
        shelf: '01',
        bin: null,
        description: 'Kệ nước mắm Nam Ngư',
        contents: [
            {
                id: 'bl-7',
                productCode: 'SP00156',
                productName: 'Nước mắm Nam Ngư 750ml',
                unit: 'Chai',
                batchCode: 'BATCH-220',
                quantity: 48,
                importPrice: 28000,
                expiryDate: '2027-06-30',
            },
        ],
    },
    {
        id: 9,
        label: 'B-03-01',
        zone: 'B',
        zoneTitle: 'Khu khô & gia vị',
        aisle: '03',
        shelf: '01',
        bin: null,
        description: 'Kệ dự phòng Coca Cola',
        contents: [
            {
                id: 'bl-2',
                productCode: 'SP00124',
                productName: 'Nước giải khát Coca Cola 330ml',
                unit: 'Lon',
                batchCode: 'BATCH-101',
                quantity: 40,
                importPrice: 10000,
                expiryDate: '2026-12-31',
            },
        ],
    },
    {
        id: 10,
        label: 'C-01-03',
        zone: 'C',
        zoneTitle: 'Khu đông lạnh & kem',
        aisle: '01',
        shelf: '03',
        bin: '03',
        description: 'Tủ đông kem Magnum',
        contents: [
            {
                id: 'bl-9',
                productCode: 'SP00412',
                productName: "Kem Wall's Magnum Classic",
                unit: 'Cây',
                batchCode: 'BATCH-045',
                quantity: 18,
                importPrice: 22000,
                expiryDate: '2026-06-18',
            },
        ],
    },
    {
        id: 11,
        label: 'C-02-01',
        zone: 'C',
        zoneTitle: 'Khu đông lạnh & kem',
        aisle: '02',
        shelf: '01',
        bin: null,
        description: 'Tủ đông ngăn trên',
        contents: [],
    },
];

/**
 * Lô đã nhập kho nhưng chưa được xếp lên kệ (chưa có batch_locations).
 * Dùng cho popup Điều chỉnh — kéo thả vào kệ.
 */
export const MOCK_UNPLACED_BATCHES = [
    {
        id: 'unplaced-1',
        productCode: 'SP00124',
        productName: 'Nước giải khát Coca Cola 330ml',
        unit: 'Lon',
        batchCode: 'BATCH-130',
        quantity: 80,
        importPrice: 10000,
        expiryDate: '2027-03-15',
    },
    {
        id: 'unplaced-2',
        productCode: 'SP00089',
        productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
        unit: 'Hộp',
        batchCode: 'BATCH-206',
        quantity: 50,
        importPrice: 32000,
        expiryDate: '2026-10-15',
    },
    {
        id: 'unplaced-3',
        productCode: 'SP00178',
        productName: 'Mì Hảo Hảo tôm chua cay',
        unit: 'Gói',
        batchCode: 'BATCH-302',
        quantity: 200,
        importPrice: 3200,
        expiryDate: '2026-11-01',
    },
    {
        id: 'unplaced-4',
        productCode: 'SP00412',
        productName: "Kem Wall's Magnum Classic",
        unit: 'Cây',
        batchCode: 'BATCH-046',
        quantity: 24,
        importPrice: 22000,
        expiryDate: '2026-07-20',
    },
    {
        id: 'unplaced-5',
        productCode: 'SP00042',
        productName: 'Gạo ST25 Hạt Ngọc Trời 5kg',
        unit: 'Bao',
        batchCode: 'BATCH-313',
        quantity: 15,
        importPrice: 125000,
        expiryDate: '2027-06-30',
    },
    {
        id: 'unplaced-6',
        productCode: 'SP00331',
        productName: 'Pepsi 330ml',
        unit: 'Lon',
        batchCode: 'BATCH-125',
        quantity: 96,
        importPrice: 9500,
        expiryDate: '2026-12-01',
    },
];

export function getStorageLocations() {
    return MOCK_STORAGE_LOCATIONS;
}

export function getStorageLocationById(id) {
    return MOCK_STORAGE_LOCATIONS.find((item) => item.id === Number(id)) ?? null;
}

export function getUnplacedBatches() {
    return MOCK_UNPLACED_BATCHES.map((item) => ({ ...item }));
}
