import { IMPORT_ORDER_STATUS } from '../constants';
import { MOCK_STORAGE_LOCATIONS } from '../../storage-location/api/mockData';

export { MOCK_STORAGE_LOCATIONS };

export const MOCK_SUPPLIERS = [
    { id: 1, name: 'Công ty TNHH Coca-Cola Việt Nam', code: 'NCC-001' },
    { id: 2, name: 'Vinamilk - Chi nhánh TP.HCM', code: 'NCC-002' },
    { id: 3, name: 'Công ty CP Thực phẩm Cholimex', code: 'NCC-003' },
    { id: 4, name: 'Unilever Việt Nam', code: 'NCC-004' },
    { id: 5, name: 'Công ty TNHH Acecook Việt Nam', code: 'NCC-005' },
];

/** Sản phẩm dùng cho tìm kiếm khi tạo phiếu nhập */
export const MOCK_IMPORT_PRODUCTS = [
    {
        id: 1,
        productCode: 'SP00124',
        productName: 'Nước giải khát Coca Cola 330ml',
        unit: 'Lon',
        barcode: '8934567890123',
        defaultCost: 10000,
        hasExpiry: true,
    },
    {
        id: 2,
        productCode: 'SP00089',
        productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
        unit: 'Hộp',
        barcode: '8934567890456',
        defaultCost: 32000,
        hasExpiry: true,
    },
    {
        id: 3,
        productCode: 'SP00201',
        productName: 'Trứng gà ta',
        unit: 'Quả',
        barcode: '8934567890789',
        defaultCost: 4500,
        hasExpiry: true,
    },
    {
        id: 4,
        productCode: 'SP00042',
        productName: 'Gạo ST25 Hạt Ngọc Trời 5kg',
        unit: 'Bao',
        barcode: '8934567891012',
        defaultCost: 125000,
        hasExpiry: false,
    },
    {
        id: 5,
        productCode: 'SP00331',
        productName: 'Pepsi 330ml',
        unit: 'Lon',
        barcode: '8934567891345',
        defaultCost: 9500,
        hasExpiry: true,
    },
    {
        id: 6,
        productCode: 'SP00156',
        productName: 'Nước mắm Nam Ngư 750ml',
        unit: 'Chai',
        barcode: '8934567891678',
        defaultCost: 28000,
        hasExpiry: true,
    },
    {
        id: 7,
        productCode: 'SP00178',
        productName: 'Mì Hảo Hảo tôm chua cay',
        unit: 'Gói',
        barcode: '8934567891901',
        defaultCost: 3200,
        hasExpiry: true,
    },
    {
        id: 8,
        productCode: 'SP00412',
        productName: "Kem Wall's Magnum Classic",
        unit: 'Cây',
        barcode: '8934567892234',
        defaultCost: 22000,
        hasExpiry: true,
    },
];

export const MOCK_IMPORT_ORDERS = [
    {
        id: 'PO-20231028-001',
        orderCode: 'PO-20231028-001',
        supplierId: 1,
        supplierName: 'Công ty TNHH Coca-Cola Việt Nam',
        receivedDate: '2023-10-28T09:15:00',
        createdByName: 'Nguyễn Văn A',
        totalCost: 4850000,
        status: IMPORT_ORDER_STATUS.RECEIVED,
        note: 'Nhập hàng định kỳ tuần 4',
        itemCount: 3,
        totalQuantity: 420,
    },
    {
        id: 'PO-20231027-002',
        orderCode: 'PO-20231027-002',
        supplierId: 2,
        supplierName: 'Vinamilk - Chi nhánh TP.HCM',
        receivedDate: '2023-10-27T14:30:00',
        createdByName: 'Trần Thị B',
        totalCost: 12800000,
        status: IMPORT_ORDER_STATUS.RECEIVED,
        note: '',
        itemCount: 2,
        totalQuantity: 400,
    },
    {
        id: 'PO-20231026-003',
        orderCode: 'PO-20231026-003',
        supplierId: 5,
        supplierName: 'Công ty TNHH Acecook Việt Nam',
        receivedDate: '2023-10-26T10:00:00',
        createdByName: 'Lê Văn C',
        totalCost: 960000,
        status: IMPORT_ORDER_STATUS.DELIVERING,
        note: 'Đơn đang trên đường giao',
        itemCount: 1,
        totalQuantity: 300,
    },
    {
        id: 'PO-20231020-004',
        orderCode: 'PO-20231020-004',
        supplierId: 3,
        supplierName: 'Công ty CP Thực phẩm Cholimex',
        receivedDate: '2023-10-20T08:45:00',
        createdByName: 'Phạm Thị D',
        totalCost: 2250000,
        status: IMPORT_ORDER_STATUS.CANCELLED,
        note: 'Hủy do nhập sai NCC',
        itemCount: 2,
        totalQuantity: 150,
    },
    {
        id: 'PO-20231018-005',
        orderCode: 'PO-20231018-005',
        supplierId: 4,
        supplierName: 'Unilever Việt Nam',
        receivedDate: '2023-10-18T16:20:00',
        createdByName: 'Nguyễn Văn A',
        totalCost: 6720000,
        status: IMPORT_ORDER_STATUS.RECEIVED,
        note: 'Nhập bổ sung kệ B',
        itemCount: 4,
        totalQuantity: 280,
    },
    {
        id: 'PO-20231015-006',
        orderCode: 'PO-20231015-006',
        supplierId: 1,
        supplierName: 'Công ty TNHH Coca-Cola Việt Nam',
        receivedDate: '2023-10-15T11:00:00',
        createdByName: 'Trần Thị B',
        totalCost: 3100000,
        status: IMPORT_ORDER_STATUS.RECEIVED,
        note: '',
        itemCount: 2,
        totalQuantity: 310,
    },
];

/** Mỗi dòng = 1 lô sẽ được tạo khi nhập hàng */
export const MOCK_IMPORT_ORDER_LINES = {
    'PO-20231028-001': [
        {
            id: 'line-1',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            quantity: 200,
            costPerUnit: 10000,
            expiryDate: '2026-12-31',
            locationLabel: 'A-01-02',
            batchCode: 'BATCH-101',
        },
        {
            id: 'line-2',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            quantity: 120,
            costPerUnit: 10200,
            expiryDate: '2026-08-15',
            locationLabel: 'A-01-02',
            batchCode: 'BATCH-119',
        },
        {
            id: 'line-3',
            productCode: 'SP00331',
            productName: 'Pepsi 330ml',
            unit: 'Lon',
            quantity: 100,
            costPerUnit: 9500,
            expiryDate: '2026-09-20',
            locationLabel: 'A-02-02',
            batchCode: 'BATCH-118',
        },
    ],
    'PO-20231027-002': [
        {
            id: 'line-1',
            productCode: 'SP00089',
            productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
            unit: 'Hộp',
            quantity: 200,
            costPerUnit: 32000,
            expiryDate: '2026-11-30',
            locationLabel: 'A-01-03',
            batchCode: 'BATCH-205',
        },
        {
            id: 'line-2',
            productCode: 'SP00089',
            productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
            unit: 'Hộp',
            quantity: 200,
            costPerUnit: 32000,
            expiryDate: '2026-10-15',
            locationLabel: '',
            batchCode: 'BATCH-206',
        },
    ],
    'PO-20231026-003': [
        {
            id: 'line-1',
            productCode: 'SP00178',
            productName: 'Mì Hảo Hảo tôm chua cay',
            unit: 'Gói',
            quantity: 300,
            costPerUnit: 3200,
            expiryDate: '2026-09-20',
            locationLabel: '',
            batchCode: null,
        },
    ],
    'PO-20231020-004': [
        {
            id: 'line-1',
            productCode: 'SP00201',
            productName: 'Trứng gà ta',
            unit: 'Quả',
            quantity: 100,
            costPerUnit: 4500,
            expiryDate: '2026-06-15',
            locationLabel: 'A-02-01',
            batchCode: 'BATCH-088',
        },
        {
            id: 'line-2',
            productCode: 'SP00042',
            productName: 'Gạo ST25 Hạt Ngọc Trời 5kg',
            unit: 'Bao',
            quantity: 50,
            costPerUnit: 125000,
            expiryDate: '',
            locationLabel: 'A-03-02',
            batchCode: 'BATCH-312',
        },
    ],
    'PO-20231018-005': [
        {
            id: 'line-1',
            productCode: 'SP00156',
            productName: 'Nước mắm Nam Ngư 750ml',
            unit: 'Chai',
            quantity: 80,
            costPerUnit: 28000,
            expiryDate: '2027-06-30',
            locationLabel: 'B-02-01',
            batchCode: 'BATCH-220',
        },
        {
            id: 'line-2',
            productCode: 'SP00178',
            productName: 'Mì Hảo Hảo tôm chua cay',
            unit: 'Gói',
            quantity: 120,
            costPerUnit: 3200,
            expiryDate: '2026-09-20',
            locationLabel: 'B-01-01',
            batchCode: 'BATCH-301',
        },
        {
            id: 'line-3',
            productCode: 'SP00412',
            productName: "Kem Wall's Magnum Classic",
            unit: 'Cây',
            quantity: 40,
            costPerUnit: 22000,
            expiryDate: '2026-06-18',
            locationLabel: 'C-01-03',
            batchCode: 'BATCH-045',
        },
        {
            id: 'line-4',
            productCode: 'SP00178',
            productName: 'Mì Hảo Hảo tôm chua cay',
            unit: 'Gói',
            quantity: 40,
            costPerUnit: 3300,
            expiryDate: '2026-11-01',
            locationLabel: '',
            batchCode: 'BATCH-302',
        },
    ],
    'PO-20231015-006': [
        {
            id: 'line-1',
            productCode: 'SP00124',
            productName: 'Nước giải khát Coca Cola 330ml',
            unit: 'Lon',
            quantity: 160,
            costPerUnit: 10000,
            expiryDate: '2026-12-31',
            locationLabel: 'B-03-01',
            batchCode: 'BATCH-101',
        },
        {
            id: 'line-2',
            productCode: 'SP00331',
            productName: 'Pepsi 330ml',
            unit: 'Lon',
            quantity: 150,
            costPerUnit: 9500,
            expiryDate: '2026-09-20',
            locationLabel: 'A-02-02',
            batchCode: 'BATCH-118',
        },
    ],
};

export function getImportOrderById(id) {
    return MOCK_IMPORT_ORDERS.find((item) => item.id === id) ?? null;
}

export function getImportOrderLinesById(id) {
    return MOCK_IMPORT_ORDER_LINES[id] ?? [];
}

export function getSupplierById(id) {
    return MOCK_SUPPLIERS.find((item) => item.id === Number(id)) ?? null;
}
