-- -- ============================================================
-- -- V3: Support per-unit selling price + default unit, and snapshot
-- --     the base-unit quantity deducted from warehouse stock.
-- --
-- --     product_units.selling_price       price for THIS unit (e.g. a "Thùng"
-- --                                        may be cheaper per-piece than a "Cái")
-- --     product_units.is_default          which unit the POS should preselect
-- --     sales_order_details.quantity_in_base_unit
-- --                                        quantity * unit_base at sale time,
-- --                                        i.e. how much base-unit stock was
-- --                                        actually deducted from the warehouse.
-- -- ============================================================
--
-- ALTER TABLE product_units
--     ADD COLUMN selling_price DECIMAL(15,2) NULL AFTER unit_base,
--     ADD COLUMN is_default    TINYINT(1) NOT NULL DEFAULT 0 AFTER selling_price;
--
-- ALTER TABLE sales_order_details
--     ADD COLUMN quantity_in_base_unit DECIMAL(10,4) NULL AFTER quantity;
--
-- -- ------------------------------------------------------------
-- -- Seed: make sure every product has a base unit, then give a
-- -- subset of products a second, larger unit so the POS has real
-- -- multi-unit products to test the unit dropdown against.
-- -- ------------------------------------------------------------
--
-- -- 1) Base unit ("Cái", unit_base = 1) for any product that has none yet.
-- INSERT INTO product_units (product_id, name, unit_base, selling_price, is_default, created_at, updated_at, is_removed)
-- SELECT p.id, 'Cái', 1.0000, p.selling_price, 1, NOW(), NOW(), 0
-- FROM products p
-- WHERE NOT EXISTS (
--     SELECT 1 FROM product_units pu WHERE pu.product_id = p.id
-- );
--
-- -- 2) A bulk unit ("Thùng", 12x base) for products that only have the base
-- --    unit so far — demonstrates a product sold in multiple units.
-- INSERT INTO product_units (product_id, name, unit_base, selling_price, is_default, created_at, updated_at, is_removed)
-- SELECT p.id, 'Thùng', 12.0000, p.selling_price * 12, 0, NOW(), NOW(), 0
-- FROM products p
-- WHERE (SELECT COUNT(*) FROM product_units pu WHERE pu.product_id = p.id) = 1;
